// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // CLI (`migrate deploy`) cần một kết nối **session** thật: migration chạy
    // DDL trong transaction dài và advisory lock mức session, thứ mà
    // transaction-mode pooler (DATABASE_URL, cổng 6543) không giữ được. App lúc
    // chạy thì đọc DATABASE_URL trong PrismaService, không qua file này.
    // `||` chứ không `??`: `DIRECT_URL=` để trống phải rơi về DATABASE_URL.
    url: process.env["DIRECT_URL"] || process.env["DATABASE_URL"],
  },
});
