export const ERROR_CODES = {
  EMAIL_ALREADY_EXISTS: 'AUTH_EMAIL_ALREADY_EXISTS',
  INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  INVALID_REFRESH_TOKEN: 'AUTH_INVALID_REFRESH_TOKEN',
  REFRESH_TOKEN_REUSED: 'AUTH_REFRESH_TOKEN_REUSED',
  USER_NOT_FOUND: 'AUTH_USER_NOT_FOUND',
  ACCOUNT_NOT_ACTIVE: 'AUTH_ACCOUNT_NOT_ACTIVE',
  GOOGLE_ACCOUNT_ONLY: 'AUTH_GOOGLE_ACCOUNT_ONLY',
  GOOGLE_PROFILE_MISSING_EMAIL: 'AUTH_GOOGLE_PROFILE_MISSING_EMAIL',

  // Personal board. Anything belonging to someone else is reported as "not
  // found" rather than "forbidden", so the API never confirms it exists.
  BOARD_NOT_FOUND: 'BOARD_NOT_FOUND',
  LIST_NOT_FOUND: 'LIST_NOT_FOUND',
  CARD_NOT_FOUND: 'CARD_NOT_FOUND',
  LABEL_NOT_FOUND: 'LABEL_NOT_FOUND',
  CHECKLIST_NOT_FOUND: 'CHECKLIST_NOT_FOUND',
  CHECKLIST_ITEM_NOT_FOUND: 'CHECKLIST_ITEM_NOT_FOUND',
  NOTE_NOT_FOUND: 'NOTE_NOT_FOUND',
  ATTACHMENT_NOT_FOUND: 'ATTACHMENT_NOT_FOUND',
  /** Advisory only — returned as a `warning` flag on a 200, never as an error. */
  LIST_WIP_EXCEEDED: 'LIST_WIP_EXCEEDED',
  CARD_NOT_IN_BOARD: 'CARD_NOT_IN_BOARD',
  INVALID_TIMEZONE: 'INVALID_TIMEZONE',

  /** Body sai ràng buộc trên controller gắn `Validation422Filter`. */
  VALIDATION_FAILED: 'VALIDATION_FAILED',

  // Dự án. Giống bảng: dự án của người khác báo "không tìm thấy" chứ không
  // "không có quyền", để API không xác nhận id đó có tồn tại.
  PROJECT_NOT_FOUND: 'PROJECT_NOT_FOUND',
  PROJECT_CODE_TAKEN: 'PROJECT_CODE_TAKEN',
  PROJECT_NAME_TAKEN: 'PROJECT_NAME_TAKEN',
  PROJECT_LIMIT_REACHED: 'PROJECT_LIMIT_REACHED',
  PROJECT_LAST_ONE: 'PROJECT_LAST_ONE',
  PROJECT_NOT_EMPTY: 'PROJECT_NOT_EMPTY',
  PROJECT_ARCHIVED: 'PROJECT_ARCHIVED',
  PROJECT_SYSTEM_LOCKED: 'PROJECT_SYSTEM_LOCKED',
} as const;
