export const ERROR_CODES = {
  EMAIL_ALREADY_EXISTS: 'AUTH_EMAIL_ALREADY_EXISTS',
  INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  INVALID_REFRESH_TOKEN: 'AUTH_INVALID_REFRESH_TOKEN',
  REFRESH_TOKEN_REUSED: 'AUTH_REFRESH_TOKEN_REUSED',
  USER_NOT_FOUND: 'AUTH_USER_NOT_FOUND',
  ACCOUNT_NOT_ACTIVE: 'AUTH_ACCOUNT_NOT_ACTIVE',
  GOOGLE_ACCOUNT_ONLY: 'AUTH_GOOGLE_ACCOUNT_ONLY',
  GOOGLE_PROFILE_MISSING_EMAIL: 'AUTH_GOOGLE_PROFILE_MISSING_EMAIL',
} as const;
